---
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: tfserving-predict-mapping-MODEL_NAME
      prefix: tfserving/models/MODEL_NAME/
      rewrite: /v1/models/MODEL_NAME:predict
      method: POST
      service: MODEL_NAME.kubeflow:8500
  labels:
    app: MODEL_NAME
  name: SERVICE_NAME
  namespace: KUBEFLOW_NAMESPACE
spec:
  ports:
  - name: tf-serving-builtin-http
    port: 8500
    targetPort: 8500
  selector:
    app: SERVICE_NAME
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: SERVICE_NAME
  name: SERVICE_NAME
  namespace: KUBEFLOW_NAMESPACE
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: SERVICE_NAME
        version: v1
    spec:
      containers:
      - args:
        - --rest_api_port=8500
        - --model_name=MODEL_NAME
        - --model_base_path=MODEL_PATH
        command:
        - /usr/bin/tensorflow_model_server
        image: tensorflow/serving
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          tcpSocket:
            port: 8500
        name: MODEL_NAME
        ports:
        - containerPort: 8500
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 1Gi
